on:
  workflow_dispatch:
  # run every Monday at noon UTC
  schedule:
    - cron:  '0 12 * * 1'

permissions:
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: pull-request
        run: |
          gh_pr_up() { gh pr create $* || gh pr edit $* }
          gh_pr_up --title "chore: sync eth upstream" --body "" --assignee '@lgray' --base master --head go-ethereum:master
