name: amd64 linux tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  # Run daily at 0:01 UTC
  schedule:
    - cron:  '1 0 * * *'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '>=1.21.4'
      - name: Run tests
        run: make test
        env:
          GOOS: linux
          GOARCH: amd64
