name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  # Run daily at 0:01 UTC
  schedule:
    - cron:  '1 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: build-and-test (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.4'
      - name: Run tests
        run: make test
        env:
          GOOS: linux
          GOARCH: amd64

  pass:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "All jobs passed"
